name: node
description: App Description
ignoreFiles: .git .next .idea node_modules
modules:
- name: nocodedb
  language: nodejs12.x
  web: express
  description: Module description
  prebuildScript: ./install.sh
  functions:
  - name: entry
    entry: entry.js
    description: the entry point for the function
